const params=new URLSearchParams(location.search);document.body.classList.toggle('embedded',params.has('embed'));
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
let visible=!params.has('preview'),playing=false,paused=false,score=0,high=Number(localStorage.getItem('arcade-high')||0),ship=176,dir=0,bullets=[],enemies=[],last=0,elapsed=0,cooldown=0,wave=1,lives=3;
const alien=['0011100','0111110','1101011','1111111','0101010','1000001'];
function pixels(pattern,x,y,size=3){ctx.fillStyle='#ffac32';for(let r=0;r<pattern.length;r++)for(let c=0;c<pattern[r].length;c++)if(pattern[r][c]==='1')ctx.fillRect(x+c*size,y+r*size,size,size)}
function spawn(){enemies=[];for(let r=0;r<3;r++)for(let c=0;c<6;c++)enemies.push({x:48+c*44,y:65+r*29});}
function start(){if(playing){paused=!paused;return}score=0;lives=3;wave=1;ship=176;bullets=[];elapsed=0;spawn();playing=true;paused=false;draw();}
function fire(){if(!playing){start();return}if(paused||cooldown>0)return;bullets.push({x:ship,y:202});cooldown=.18;}
function action(name){if(name==='coin'){playing=false;start()}else if(name==='start')start();else fire();}
document.querySelectorAll('[data-action]').forEach(el=>{const hit=()=>{el.classList.add('down');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('down'),200);action(el.dataset.action)};el.addEventListener('pointerdown',e=>{e.preventDefault();hit()});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();hit()}})});
const stick=document.querySelector('#stick'),joy=document.querySelector('#joystick');let dragging=false,origin=0;
function steer(value){dir=value;stick.style.transform=`translate(${value*9}px,${value*2}px)`;joy.setAttribute('aria-valuenow',value)}
joy.addEventListener('pointerdown',e=>{dragging=true;origin=e.clientX;joy.setPointerCapture(e.pointerId);if(!playing)start()});joy.addEventListener('pointermove',e=>{if(dragging)steer(Math.abs(e.clientX-origin)<4?0:Math.sign(e.clientX-origin))});joy.addEventListener('pointerup',()=>{dragging=false;steer(0)});joy.addEventListener('pointercancel',()=>{dragging=false;steer(0)});
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' ','Enter','p','P'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')steer(-1);else if(e.key==='ArrowRight')steer(1);else if(e.key===' ')fire();else if(e.key==='Enter'){if(!e.repeat)action('coin')}else if(!e.repeat)paused=!paused}});window.addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight')steer(0)});window.addEventListener('blur',()=>steer(0));
window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.type==='gallery-visibility'){visible=e.data.visible;last=0}});
function draw(){const bg=ctx.createRadialGradient(176,116,15,176,116,210);bg.addColorStop(0,'#482306');bg.addColorStop(1,'#180d07');ctx.fillStyle=bg;ctx.fillRect(0,0,352,241);ctx.font='bold 12px monospace';ctx.fillStyle='#ffb442';ctx.shadowColor='#f88127';ctx.shadowBlur=5;ctx.fillText('1UP',22,23);ctx.fillText(String(score).padStart(6,'0'),22,38);ctx.fillText('HI-SCORE',248,23);ctx.fillText(String(high).padStart(6,'0'),255,38);
 const list=playing?enemies:Array.from({length:18},(_,i)=>({x:48+(i%6)*44+Math.sin(elapsed)*5,y:65+Math.floor(i/6)*29}));for(const e of list)pixels(alien,e.x,e.y,3);
 pixels(['0001000','0011100','0111110','1111111'],ship-14,204,4);for(const b of bullets)ctx.fillRect(b.x-1,b.y,3,8);for(let i=0;i<lives;i++)ctx.fillRect(21+i*13,222,8,4);ctx.shadowBlur=0;
 if(!playing||paused){ctx.fillStyle='#1c100bb8';ctx.fillRect(54,157,244,29);ctx.fillStyle='#ffc064';ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText(paused?'PAUSED':score?'GAME OVER · INSERT COIN':'INSERT COIN · PRESS ENTER',176,176);ctx.textAlign='left'}
 ctx.fillStyle='#00000017';for(let y=0;y<241;y+=3)ctx.fillRect(0,y,352,1);
}
function frame(t){requestAnimationFrame(frame);if(!visible||document.hidden){last=0;return}if(t-last<33)return;const dt=Math.min((t-last)/1000,.05);last=t;elapsed+=dt;if(playing&&!paused){ship=Math.max(22,Math.min(330,ship+dir*160*dt));cooldown-=dt;for(const b of bullets)b.y-=210*dt;for(const e of enemies){e.x+=Math.cos(elapsed*.8)*dt*(13+wave*3);e.y+=dt*(1.8+wave*.5)}for(const b of bullets){const target=enemies.find(e=>b.x>e.x-3&&b.x<e.x+24&&b.y>e.y-5&&b.y<e.y+20);if(target){enemies.splice(enemies.indexOf(target),1);b.y=-20;score+=100;if(score>high){high=score;localStorage.setItem('arcade-high',high)}}}bullets=bullets.filter(b=>b.y>-10);if(enemies.some(e=>e.y>195)){lives--;if(!lives)playing=false;else spawn()}if(!enemies.length){wave++;spawn()}}draw()}
window.arcadeGame={action,steer,getState:()=>({playing,paused,score,ship})};spawn();draw();requestAnimationFrame(frame);
