import * as T from 'three';
import {RoundedBoxGeometry} from './vendor/RoundedBoxGeometry.js';
import {createFrameGate,configurePreview} from './preview-performance.js?v=53';
const stage=document.querySelector('#arcade-stage'),game=window.arcadeGame;
const renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;stage.append(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','迷你街机：Enter 投币，方向键移动，空格发射，P 暂停，或点击实体按钮。');
const scene=new T.Scene(),body=new T.Group();scene.add(body);const camera=new T.OrthographicCamera(-5,5,5,-5,.1,50);camera.position.set(8,8.1,12);camera.lookAt(0,3.2,0);
scene.add(new T.HemisphereLight(0xffffff,0xdcd9d2,1.7));const key=new T.DirectionalLight(0xffffff,1.8);key.position.set(-5,10,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-7,right:7,top:8,bottom:-5,near:.1,far:30});key.shadow.normalBias=.035;scene.add(key);const fill=new T.DirectionalLight(0xffffff,.65);fill.position.set(8,5,7);scene.add(fill);
const white=new T.MeshStandardMaterial({color:0xf1eee8,roughness:.75,metalness:.12}),grey=new T.MeshStandardMaterial({color:0x888b85,roughness:.6,metalness:.3}),dark=new T.MeshStandardMaterial({color:0x363833,roughness:.72}),orange=new T.MeshStandardMaterial({color:0xff790e,roughness:.35,emissive:0xff6500,emissiveIntensity:0}),edge=new T.LineBasicMaterial({color:0x51534d});
function mesh(g,m,p=[0,0,0],parent=body,outline=true){const o=new T.Mesh(g,m);o.position.set(...p);parent.add(o);o.castShadow=true;o.receiveShadow=true;if(outline){const e=new T.LineSegments(new T.EdgesGeometry(g,26),edge);e.raycast=()=>{};o.add(e)}return o}
function box(w,h,d,r,m,p,parent=body){return mesh(new RoundedBoxGeometry(w,h,d,2,r),m,p,parent)}
function label(text,w,h,p,parent=body){const c=document.createElement('canvas');c.width=256;c.height=96;const x=c.getContext('2d');x.font='bold 62px monospace';x.textAlign='center';x.textBaseline='middle';x.fillStyle='#f88127';x.fillText(text,128,48);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}),p,parent,false)}
const outline=[[-1.5,.35],[2.15,.35],[2.15,1.95],[.74,2.65],[.40,5.45],[1.18,5.95],[1.18,6.6],[-1.5,6.6]];
for(const x of [-2.06,1.92]){const s=new T.Shape(),points=outline.map(([z,y])=>new T.Vector2(-z,y));for(let i=0;i<points.length;i++){const v=points[i],prev=points[(i+points.length-1)%points.length],next=points[(i+1)%points.length],r=Math.min(.15,v.distanceTo(prev)*.22,v.distanceTo(next)*.22),a=v.clone().add(prev.clone().sub(v).normalize().multiplyScalar(r)),b=v.clone().add(next.clone().sub(v).normalize().multiplyScalar(r));if(i===0)s.moveTo(a.x,a.y);else s.lineTo(a.x,a.y);s.quadraticCurveTo(v.x,v.y,b.x,b.y)}s.closePath();const o=mesh(new T.ExtrudeGeometry(s,{depth:.14,bevelEnabled:true,bevelSize:.045,bevelThickness:.035,bevelSegments:3,curveSegments:12}),white,[x,0,0]);o.rotation.y=Math.PI/2;}
box(3.92,6.16,.10,.035,white,[0,3.48,-1.48]);box(3.95,.10,2.67,.03,white,[0,6.58,-.16]);box(3.9,1.56,.12,.045,white,[0,1.17,2.12]);
function panel(y1,z1,y2,z2){const g=new T.Group();g.position.set(0,(y1+y2)/2,(z1+z2)/2);g.rotation.x=Math.atan2(z2-z1,y2-y1);body.add(g);box(3.86,Math.hypot(y2-y1,z2-z1),.12,.035,white,[0,0,0],g);return g}
const deck=panel(1.96,2.10,2.64,.72),display=panel(2.65,.72,5.43,.38);panel(5.44,.39,5.96,1.17);const marquee=panel(5.98,1.18,6.56,1.18);box(3.64,.43,.035,.025,white,[0,0,.08],marquee);label('ARCADE',1.85,.26,[0,0,.102],marquee);for(const x of [-1.38,1.38])for(const y of [-.055,.055])box(.48,.036,.018,.005,orange,[x,y,.103],marquee);
box(3.47,2.53,.14,.13,dark,[0,0,.09],display);box(3.24,2.30,.045,.12,new T.MeshStandardMaterial({color:0x49473e,roughness:.55}),[0,0,.175],display);const texture=new T.CanvasTexture(document.querySelector('#game'));texture.colorSpace=T.SRGBColorSpace;texture.magFilter=T.NearestFilter;texture.minFilter=T.LinearFilter;
function roundedScreen(w,h,r){const s=new T.Shape();s.moveTo(-w/2+r,-h/2);s.lineTo(w/2-r,-h/2);s.quadraticCurveTo(w/2,-h/2,w/2,-h/2+r);s.lineTo(w/2,h/2-r);s.quadraticCurveTo(w/2,h/2,w/2-r,h/2);s.lineTo(-w/2+r,h/2);s.quadraticCurveTo(-w/2,h/2,-w/2,h/2-r);s.lineTo(-w/2,-h/2+r);s.quadraticCurveTo(-w/2,-h/2,-w/2+r,-h/2);const g=new T.ShapeGeometry(s,24),p=g.attributes.position,uv=g.attributes.uv;for(let i=0;i<p.count;i++)uv.setXY(i,p.getX(i)/w+.5,p.getY(i)/h+.5);return g}
mesh(roundedScreen(3.08,2.14,.16),new T.MeshBasicMaterial({map:texture}),[0,0,.201],display,false);mesh(roundedScreen(3.08,2.14,.16),new T.MeshPhysicalMaterial({color:0xffffff,transparent:true,opacity:.045,roughness:.13,clearcoat:1,depthWrite:false}),[0,0,.216],display,false);
for(const x of [-1.78,1.78])for(const y of [-.62,.62]){const o=mesh(new T.CylinderGeometry(.065,.065,.024,24),grey,[x,y,.09],deck);o.rotation.x=Math.PI/2;box(.057,.010,.003,.002,dark,[x,y,.104],deck)}
const buttons=[];for(const [x,y,action]of [[.60,-.30,'fire'],[1.25,-.30,'fire'],[.94,.34,'start']]){const b=mesh(new T.CylinderGeometry(.191,.199,.06,40),dark,[x,y,.10],deck);b.rotation.x=Math.PI/2;const g=new T.Group();g.position.set(x,y,.15);g.scale.setScalar(.78);deck.add(g);const material=orange.clone(),profile=[[0,-.055],[.20,-.055],[.222,-.025],[.222,.025],[.204,.060],[.18,.067],[0,.067]].map(p=>new T.Vector2(...p)),cap=mesh(new T.LatheGeometry(profile,48),material,[0,0,0],g);cap.rotation.x=Math.PI/2;cap.userData.action=action;buttons.push({g,cap,down:false,until:0,material});}
const joyGroup=new T.Group();joyGroup.position.set(-.96,-.06,.11);deck.add(joyGroup);const base=mesh(new T.CylinderGeometry(.27,.28,.055,40),dark,[0,0,0],joyGroup);base.rotation.x=Math.PI/2;const stick=new T.Group();stick.rotation.x=0;joyGroup.add(stick);const shaft=mesh(new T.CylinderGeometry(.043,.043,.46,24),grey,[0,0,.26],stick);shaft.rotation.x=Math.PI/2;const ball=mesh(new T.SphereGeometry(.245,32,24),orange,[0,0,.52],stick,false);ball.userData.action='joystick';
box(.46,.65,.105,.045,dark,[.75,1.1,2.23]);box(.34,.52,.032,.018,grey,[.75,1.1,2.298]);box(.045,.36,.02,.008,dark,[.65,1.1,2.325]);const coinMat=orange.clone();coinMat.emissiveIntensity=.8;const coin=box(.065,.35,.045,.012,coinMat,[.81,1.1,2.332]);coin.userData.action='coin';
for(const x of [-2.11,2.11]){box(.025,1.30,1.12,.02,white,[x,1.32,-.69]);for(let i=0;i<3;i++)box(.028,.036,.48,.008,dark,[x+(x>0?.02:-.02),1.14+i*.14,-.7]);for(const y of [.59,1.88,6.14])for(const z of [-1.15,.17]){const s=mesh(new T.CylinderGeometry(.055,.055,.03,24),grey,[x,y,z]);s.rotation.z=Math.PI/2;}}
function stripe(x,offset){const points=[[x,5.70,-1.40+offset],[x,5.16,-.83+offset],[x,.40,.94+offset]];for(let i=0;i<2;i++){const a=new T.Vector3(...points[i]),b=new T.Vector3(...points[i+1]),delta=b.clone().sub(a),bar=box(.014,delta.length(),.045,.005,orange,a.clone().add(b).multiplyScalar(.5).toArray());bar.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());}}
for(const x of [-2.115,2.115])for(const offset of [0,.15])stripe(x,offset);for(const x of [-1.62,1.62])for(const z of [-1.04,1.77])box(.43,.23,.45,.055,dark,[x,.22,z]);const floor=mesh(new T.PlaneGeometry(40,40),new T.ShadowMaterial({opacity:.095}),[0,.10,0],scene,false);floor.rotation.x=-Math.PI/2;floor.castShadow=false;
const ray=new T.Raycaster(),pointer=new T.Vector2();let held=null,dragX=0,last=0,paint=0;const targets=[ball,coin,...buttons.map(b=>b.cap)];
function cast(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(targets,false)[0]?.object}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;held=cast(e);if(!held)return;renderer.domElement.focus();renderer.domElement.setPointerCapture(e.pointerId);dragX=e.clientX;if(held===ball){if(!game.getState().playing)game.action('coin')}else{const b=buttons.find(b=>b.cap===held);if(b)b.down=true;}});
renderer.domElement.addEventListener('pointermove',e=>{renderer.domElement.style.cursor=cast(e)?'pointer':'default';if(held===ball){const d=T.MathUtils.clamp((e.clientX-dragX)/30,-1,1);game.steer(Math.abs(d)<.1?0:Math.sign(d));stick.rotation.y=d*.23}});
function release(){buttons.forEach(b=>b.down=false);game.steer(0);held=null;stick.rotation.y=0}renderer.domElement.addEventListener('pointerup',e=>{const o=held;if(o&&o!==ball&&cast(e)===o){game.action(o.userData.action);const b=buttons.find(b=>b.cap===o);if(b)b.until=performance.now()+220;}release()});for(const ev of ['pointercancel','lostpointercapture'])renderer.domElement.addEventListener(ev,release);window.addEventListener('blur',release);
body.scale.set(1.06,.90,1);camera.position.set(7.5,7.0,12);camera.lookAt(0,2.95,.25);key.shadow.radius=4;key.shadow.bias=-.0001;
const gate=createFrameGate(stage);configurePreview(renderer,scene,stage);function resize(){const w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;renderer.setSize(w,h);const a=w/h,span=a<.8?7.4/a:8.0;camera.left=-span*a/2;camera.right=span*a/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(stage);resize();
function tick(t){requestAnimationFrame(tick);if(document.hidden||document.documentElement.classList.contains('gallery-paused')||!gate(t))return;const dt=Math.min((t-last)/1000||.016,.05);last=t;for(const b of buttons){b.g.position.z=T.MathUtils.lerp(b.g.position.z,b.down?.11:.15,1-Math.exp(-dt*25));b.material.emissiveIntensity=T.MathUtils.lerp(b.material.emissiveIntensity,b.down||t<b.until?1.4:0,1-Math.exp(-dt*20))}if(t-paint>33){paint=t;texture.needsUpdate=true}scene.updateMatrixWorld(true);camera.updateMatrixWorld();function coords(o){const p=o.getWorldPosition(new T.Vector3()).project(camera);return[(p.x+1)*stage.clientWidth/2,(1-p.y)*stage.clientHeight/2]}stage.dataset.controls=JSON.stringify({coin:coords(coin),joystick:coords(ball),fire:coords(buttons[0].cap),start:coords(buttons[2].cap)});stage.dataset.playing=String(game.getState().playing);stage.dataset.paused=String(game.getState().paused);renderer.render(scene,camera)}requestAnimationFrame(tick);



