import {createFrameGate,configurePreview} from './preview-performance.js?v=53';
import * as T from 'three';
import {backlight as seriesBacklight} from './series-lighting.js';
import {RoundedBoxGeometry} from './vendor/RoundedBoxGeometry.js';
const stage=document.getElementById('supply-stage'),status=document.getElementById('supply-status');
const renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor(0xffffff,0);stage.append(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','交流电源。点击橙色翘板开关，MODE 切换模式，SET 进入参数设置。P 电源，M 模式，S 设置，方向键增减，R 复位。设置时 MODE 选择电压、频率或负载，SET 退出。');
const scene=new T.Scene(),camera=new T.OrthographicCamera(-5,5,4,-4,.1,40);camera.position.set(8,7.9,11);camera.lookAt(0,2.1,0);
scene.add(new T.HemisphereLight(0xffffff,0xdcd9d2,1.7));const key=new T.DirectionalLight(0xffffff,1.8);key.position.set(-5,10,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-7,right:7,top:6,bottom:-4,near:.1,far:25});key.shadow.normalBias=.035;key.shadow.bias=-.0001;scene.add(key);const fill=new T.DirectionalLight(0xffffff,.65);fill.position.set(8,5,7);scene.add(fill);
const white=new T.MeshStandardMaterial({color:0xf1eee8,roughness:.75,metalness:.12}),grey=new T.MeshStandardMaterial({color:0x888b85,roughness:.6,metalness:.3}),dark=new T.MeshStandardMaterial({color:0x363833,roughness:.72}),orange=new T.MeshStandardMaterial({color:0xff790e,roughness:.55});
const edge=new T.LineBasicMaterial({color:0x51534d}),body=new T.Group();scene.add(body);
function mesh(g,m,p=[0,0,0],parent=body,outline=true){const o=new T.Mesh(g,m);o.position.set(...p);parent.add(o);o.castShadow=true;o.receiveShadow=true;if(outline){const e=new T.LineSegments(new T.EdgesGeometry(g,26),edge);e.raycast=()=>{};o.add(e);}return o;}
function box(w,h,d,r,mat,p,parent=body){return mesh(new RoundedBoxGeometry(w,h,d,1,r),mat,p,parent);}
function shape(w,h,c){const s=new T.Shape();const pts=[[-w/2+c,-h/2],[w/2-c,-h/2],[w/2,-h/2+c],[w/2,h/2-c],[w/2-c,h/2],[-w/2+c,h/2],[-w/2,h/2-c],[-w/2,-h/2+c]];s.moveTo(...pts[0]);pts.slice(1).forEach(p=>s.lineTo(...p));s.closePath();return s;}
function line(points,parent=body){parent.add(new T.Line(new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p))),edge));}
box(6,3.9,3.4,.12,white,[0,2.23,0]);mesh(new T.ExtrudeGeometry(shape(5.96,3.86,.16),{depth:.07,bevelEnabled:true,bevelSize:.025,bevelThickness:.025,bevelSegments:1}),white,[0,2.23,1.7]);
for(const x of [-2.4,2.4])for(const z of [-1.15,1.35])box(.48,.22,.52,.05,dark,[x,.21,z]);
line([[-2.77,4.181,1.30],[2.77,4.181,1.30],[3.01,4.00,1.30],[3.01,.53,1.30]]);line([[3.011,.94,1.30],[3.011,.94,-1.47]]);
for(let i=0;i<8;i++)box(3.32,.014,.025,.006,dark,[.1,4.185,-1.03+i*.16]);for(let i=0;i<7;i++)box(.016,1.18,.026,.005,dark,[3.012,2.57,-.82+i*.22]);
for(const x of [-2.80,2.80])for(const y of [.56,3.9]){const s=mesh(new T.CylinderGeometry(.11,.11,.035,32),grey,[x,y,1.805]);s.rotation.x=Math.PI/2;const h=mesh(new T.CircleGeometry(.054,6),dark,[x,y,1.826],body,false);}
box(3.65,2.25,.095,.08,dark,[-.78,2.87,1.808]);box(3.43,2.03,.025,.04,grey,[-.78,2.87,1.864]);
const screen=mesh(new T.ShapeGeometry(shape(3.34,1.94,.06)),new T.MeshBasicMaterial({color:0x242621}),[-.78,2.87,1.885],body,false);
const c=document.createElement('canvas');c.width=1100;c.height=640;const cx=c.getContext('2d'),texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();const hud=mesh(new T.PlaneGeometry(3.3,1.9),new T.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false}),[-.78,2.87,1.890],body,false);
function label(text,w,h,p,parent=body,color='#575952'){const c=document.createElement('canvas'),x=c.getContext('2d');x.font='48px Arial';c.width=Math.ceil(x.measureText(text).width)+10;c.height=64;x.font='48px Arial';x.textAlign='center';x.textBaseline='middle';x.fillStyle=color;x.fillText(text,c.width/2,32);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();return mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}),p,parent,false);}
const switchFrame=shape(.96,1.32,.055);switchFrame.holes.push(new T.Path(shape(.73,1.08,.025).getPoints().reverse()));
mesh(new T.ExtrudeGeometry(switchFrame,{depth:.13,bevelEnabled:true,bevelSize:.016,bevelThickness:.016,bevelSegments:1}),dark,[1.97,2.85,1.816]);
mesh(new T.ShapeGeometry(shape(.74,1.09,.025)),new T.MeshBasicMaterial({color:0x141611}),[1.97,2.85,1.865],body,false);
const rocker=new T.Group();rocker.position.set(1.97,2.85,1.953);rocker.rotation.x=-.24;body.add(rocker);
const rockerFace=orange.clone();rockerFace.emissive.setHex(0xff6500);
const switchSide=new T.MeshStandardMaterial({color:0xb84909,roughness:.65});
const switchCap=box(.63,.97,.12,.027,switchSide,[0,0,0],rocker);
mesh(new T.ShapeGeometry(shape(.577,.917,.023)),rockerFace,[0,0,.061],rocker,false);
label('I',.09,.21,[0,.275,.063],rocker,'#fff5e8');label('O',.17,.21,[0,-.275,.063],rocker,'#fff5e8');
for(const x of [1.616,2.324]){const axle=mesh(new T.CylinderGeometry(.055,.055,.035,24),grey,[x,2.85,1.955]);axle.rotation.z=Math.PI/2;}
label('POWER',.81,.20,[1.97,3.67,1.80]);const lamps=[];for(const [x,name]of [[-1.98,'INPUT'],[-1.08,'OUTPUT'],[-.18,'FAULT']]){const rim=mesh(new T.CylinderGeometry(.112,.112,.045,32),dark,[x,1.23,1.804]);rim.rotation.x=Math.PI/2;const mat=new T.MeshStandardMaterial({color:0x555953,roughness:.3,emissive:0x000000});const lamp=mesh(new T.SphereGeometry(.085,24,16),mat,[x,1.23,1.837],body,false);lamp.scale.z=.6;lamps.push(lamp);label(name,.61,.16,[x,.96,1.80]);}
line([[.40,.63,1.8],[.40,1.46,1.8]]);
function backlight(w,h,x,y,z){return seriesBacklight(body,w,h,[x,y,z]);}
const rockerGlow=backlight(.86,1.20,1.97,2.85,1.965);
let rockerLight=0;
const buttons=[];for(const [name,x]of [['mode',1.03],['set',2.03]]){box(.64,.40,.05,.02,dark,[x,.99,1.812]);const g=new T.Group();g.position.set(x,.99,1.893);body.add(g);const mat=white.clone();mat.emissive.setHex(0xff6a0c);const cap=box(.60,.35,.15,.025,mat,[0,0,0],g);cap.userData.action=name;const glow=backlight(.60,.35,x,.99,1.842);buttons.push({name,g,cap,down:false,light:0,flashUntil:0,glow});label(name.toUpperCase(),.6,.18,[x,1.41,1.802]);}const floor=mesh(new T.PlaneGeometry(40,40),new T.ShadowMaterial({opacity:.095}),[0,.10,0],scene,false);floor.rotation.x=-Math.PI/2;floor.castShadow=false;floor.receiveShadow=true;
let powered=true,voltage=230,frequency=50,load=78,editing=false,selected='load',bootUntil=0,frame=0,last=0,paintAt=0,pressed=null,pressTarget=null;const ray=new T.Raycaster(),pointer=new T.Vector2(),presets=[[230,50],[220,60],[110,60]];let preset=0;
function fault(){return powered&&load>=100;}
function state(){Object.assign(stage.dataset,{powered:String(powered),voltage:String(voltage),frequency:String(frequency),load:String(load),fault:String(fault()),editing:String(editing),selected});document.getElementById('supply-power').setAttribute('aria-pressed',String(powered));paintAt=0;}
function power(value){const next=typeof value==='boolean'?value:!powered;if(next===powered)return;powered=next;editing=false;bootUntil=powered?performance.now()+650:0;state();status.textContent=powered?'电源启动':'电源关闭';}
function mode(){if(!powered)return;buttons.find(b=>b.name==='mode').flashUntil=performance.now()+200;if(editing)selected=['voltage','frequency','load'][(['voltage','frequency','load'].indexOf(selected)+1)%3];else{preset=(preset+1)%3;[voltage,frequency]=presets[preset];}state();}
function set(){if(!powered)return;buttons.find(b=>b.name==='set').flashUntil=performance.now()+200;editing=!editing;state();status.textContent=editing?'参数设置：方向键或屏幕滚轮调整，MODE 选择参数，SET 保存':'已保存参数';}
function adjust(delta){if(!powered)return;editing=true;if(selected==='load')load=T.MathUtils.clamp(load+delta*5,0,120);if(selected==='voltage')voltage=T.MathUtils.clamp(voltage+delta*5,90,260);if(selected==='frequency')frequency=T.MathUtils.clamp(frequency+delta,45,65);state();status.textContent=fault()?'过载，输出已切断':selected+' 已调整';}
function reset(){powered=true;voltage=230;frequency=50;load=78;editing=false;selected='load';preset=0;bootUntil=0;state();}
const actions={power,mode,set};document.getElementById('supply-power').onclick=power;document.getElementById('supply-mode').onclick=mode;document.getElementById('supply-set').onclick=set;document.getElementById('supply-reset').onclick=reset;
function cast(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects([switchCap,...buttons.map(b=>b.cap),screen],false)[0]?.object;}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;const o=cast(e);pressed=o===switchCap?'power':o===screen?'screen':o?.userData.action;if(pressed){renderer.domElement.focus();renderer.domElement.setPointerCapture(e.pointerId);const button=buttons.find(b=>b.name===pressed);if(button)button.down=true;if(pressed==='power'){const hit=ray.intersectObject(switchCap,false)[0];const local=switchCap.worldToLocal(hit.point.clone());pressTarget=local.y>.15?true:local.y<-.15?false:!powered;}}});
renderer.domElement.addEventListener('pointerup',e=>{const n=pressed,target=pressTarget,o=cast(e);release();if(n==='power'&&o===switchCap)power(target);else if(n==='screen'&&o===screen){if(powered){selected='load';adjust(1);}}else if(n&&o?.userData.action===n)actions[n]();});function release(){pressed=null;pressTarget=null;buttons.forEach(b=>b.down=false);}for(const ev of ['pointercancel','lostpointercapture'])renderer.domElement.addEventListener(ev,release);window.addEventListener('blur',release);renderer.domElement.addEventListener('pointermove',e=>renderer.domElement.style.cursor=cast(e)?'pointer':'default');
renderer.domElement.addEventListener('wheel',e=>{if(cast(e)===screen){e.preventDefault();adjust(e.deltaY<0?1:-1);}},{passive:false});
function active(){return document.body.dataset.product==='supply'&&!document.hidden&&document.body.dataset.paused!=='true';}
document.addEventListener('keydown',e=>{if(!active()||e.ctrlKey||e.altKey||e.metaKey||e.target.closest('button,input,select'))return;const k=e.key.toLowerCase();if(['arrowup','arrowright','arrowdown','arrowleft'].includes(k)){e.preventDefault();adjust(k==='arrowup'||k==='arrowright'?1:-1);}else if(!e.repeat){if(k==='p'||e.code==='Space'){e.preventDefault();power();}else if(k==='m')mode();else if(k==='s')set();else if(k==='r')reset();}});document.addEventListener('keyup',release);
const segments=[[[8,0],[42,0],[48,6],[42,12],[8,12],[2,6]],[[42,8],[48,2],[54,8],[54,40],[48,46],[42,40]],[[42,52],[48,46],[54,52],[54,84],[48,90],[42,84]],[[8,84],[42,84],[48,90],[42,96],[8,96],[2,90]],[[0,52],[6,46],[12,52],[12,84],[6,90],[0,84]],[[0,8],[6,2],[12,8],[12,40],[6,46],[0,40]],[[8,42],[42,42],[48,48],[42,54],[8,54],[2,48]]],codes=['abcdef','bc','abdeg','abcdg','bcfg','acdfg','acdefg','abc','abcdefg','abcdfg'];
function digits(text,x,y,scale){let offset=0;for(const n of text){if(n==='.'){cx.fillStyle='#ff9b24';cx.fillRect(x+offset,y+88*scale,7*scale,7*scale);offset+=15*scale;continue;}segments.forEach((p,i)=>{cx.fillStyle=codes[+n].includes('abcdefg'[i])?'#ff9b24':'#292c25';cx.beginPath();p.forEach(([px,py],j)=>j?cx.lineTo(x+offset+px*scale,y+py*scale):cx.moveTo(x+offset+px*scale,y+py*scale));cx.fill();});offset+=68*scale;}}
function draw(t){cx.clearRect(0,0,1100,640);function text(s,x,y,size=36,color='#9c9e96'){cx.fillStyle=color;cx.font=size+'px ui-monospace,monospace';cx.fillText(s,x,y);}text(editing?'SET '+selected.toUpperCase():'AC OUTPUT',45,70,40);const ready=t>=bootUntil,ok=ready&&!fault();digits(String(ok?voltage:0).padStart(3,'0'),60,114,1.58);text('V',410,262,58,'#ff9b24');digits((ok?frequency:0).toFixed(1).padStart(4,'0'),60,302,1.43);text('Hz',425,440,52,'#ff9b24');
for(let i=0;i<6;i++){cx.fillStyle=i<Math.ceil(load/20)?(fault()?'#ff6825':'#ff9b24'):'#40443b';cx.fillRect(815,315-i*34,120,23);}text('LOAD',800,420,36);text(load+'%',800,478,51,fault()?'#ff6825':'#ff9b24');text(!ready?'STARTING':fault()?'OVERLOAD / OUTPUT CUT':editing?'MODE: SELECT  /  ARROWS: ADJUST':'OUTPUT STABLE',45,575,26,fault()?'#ff6825':'#aa8b61');if(editing)text('SET: SAVE',805,575,22,'#ff9b24');texture.needsUpdate=true;}
function resize(){const w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;renderer.setSize(w,h);const a=w/h,span=a<.8?8.3/a:8.0;camera.left=-span*a/2;camera.right=span*a/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();scene.updateMatrixWorld(true);camera.updateMatrixWorld();function coords(o){const p=o.getWorldPosition(new T.Vector3()).project(camera);return[(p.x+1)*w/2,(1-p.y)*h/2];}stage.dataset.controls=JSON.stringify(Object.fromEntries([['power',coords(switchCap)],...buttons.map(b=>[b.name,coords(b.cap)]),['screen',coords(screen)]]));}
new ResizeObserver(resize).observe(stage);
const frameGate=createFrameGate(stage);configurePreview(renderer,scene,stage);
function tick(t){frame=0;if(!active())return;if(!frameGate(t)){frame=requestAnimationFrame(tick);return;}const dt=Math.min((t-last)/1000||.016,.05);last=t;const held=pressed==='power';const tilt=held?(pressTarget?-.30:.30):(powered?-.24:.24);rocker.rotation.x=T.MathUtils.lerp(rocker.rotation.x,tilt,1-Math.exp(-dt*24));rocker.position.z=T.MathUtils.lerp(rocker.position.z,held?1.945:1.953,1-Math.exp(-dt*24));stage.dataset.switchAngle=rocker.rotation.x.toFixed(4);stage.dataset.switchPressed=String(held);const lightTarget=held?1.1:powered?.24:0;rockerLight=T.MathUtils.lerp(rockerLight,lightTarget,1-Math.exp(-dt*(held?30:14)));rockerFace.emissiveIntensity=rockerLight;rockerGlow.opacity=rockerLight*.72;stage.dataset.powerGlow=rockerLight.toFixed(3);
buttons.forEach(b=>{b.g.position.z=T.MathUtils.lerp(b.g.position.z,b.down?1.85:1.893,1-Math.exp(-dt*24));const lit=b.down||t<b.flashUntil,target=lit?1.05:powered&&editing&&b.name==='set'?.16:0;b.light=T.MathUtils.lerp(b.light,target,1-Math.exp(-dt*(lit?30:12)));b.cap.material.emissiveIntensity=b.light;b.glow.opacity=b.light*.8;stage.dataset[b.name+'Glow']=b.light.toFixed(3);});hud.visible=powered;const ready=t>=bootUntil,output=powered&&ready&&!fault();stage.dataset.output=String(output);for(let i=0;i<3;i++){const on=i===0?powered:i===1?output:fault()&&Math.floor(t/350)%2===0;const col=[0xff830a,0x78de22,0xff3d16][i];lamps[i].material.color.setHex(on?col:0x535950);lamps[i].material.emissive.setHex(on?col:0);lamps[i].material.emissiveIntensity=.35;}if(powered&&t-paintAt>120){paintAt=t;draw(t);}scene.updateMatrixWorld(true);const coords=JSON.parse(stage.dataset.controls||'{}');const w=stage.clientWidth,h=stage.clientHeight;for(const [name,y]of [['powerOn',.275],['powerOff',-.275]]){const p=rocker.localToWorld(new T.Vector3(0,y,.063)).project(camera);coords[name]=[(p.x+1)*w/2,(1-p.y)*h/2];}stage.dataset.controls=JSON.stringify(coords);renderer.render(scene,camera);frame=requestAnimationFrame(tick);}
function start(){if(active()&&!frame){resize();last=performance.now();frame=requestAnimationFrame(tick);}}
document.addEventListener('productchange',()=>{release();if(active())start();else{cancelAnimationFrame(frame);frame=0;}});document.addEventListener('visibilitychange',()=>{release();if(document.hidden){cancelAnimationFrame(frame);frame=0;}else start();});state();start();







